modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="rg"
version="${file.jarVersion}"
displayName="RickGun"
authors="anar4732"
description='''
Adds portal gun from Rick and Morty
'''

[[dependencies.rg]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"